[env.tdce]
command = """
    cargo build --features float --bin tdce -qq && \
     bril2json < {filename} | \
     ./target/debug/tdce | \
     brili"""
[env.lvn]
command = """
    cargo build --features float --bin lvn -qq && \
    bril2json < {filename} | \
    ./target/debug/lvn | \
    brili
"""
[env.baseline]
command = "bril2json < {filename} | brili"
